### ISSUE TITLE
Cannot save to S3 as part of a callback. 

### ISSUE THREAD

**Issue by IanCaunce** [robbiepaul/cloudconvert-laravel#12]
I have been trying in vein to say a file to S3 as part of a callback.

The code I have tried is:

``` php
CloudConvert::useProcess($processUrl)
    ->save(CloudConvert::S3('some/aws/key.pdf'));
```

No errors are thrown. It simply doesn't upload the file. Is this something which is supported?

As a temporary workaround I use the following code:

``` php
$cloudConvert = CloudConvert::useProcess($processUrl);

$file = $cloudConvert->getProcess()->download();

Storage::put('some/aws/key.pdf', $file);
```

Thanks, Ian

**Comment by robbiepaul** [comment]
Hi Ian,

Saving to S3 storage is a feature of the official API (https://cloudconvert.com/apidoc#s3) as such needs to be defined when the process begins. CloudConvert will automatically save the file to your bucket when the process is complete.

I haven't had a chance to test it yet but this should work:

``` php
CloudConvert::file('/a/path/to/file.doc')
            ->callback('http://myserver.com/callback.php')
            ->convert(CloudConvert::S3('some/aws/key.pdf'));
```

**Comment by IanCaunce** [comment]
I misinterpretation its functionality. Thanks for the reply.
