### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by pierrepavlov** [robbiepaul/cloudconvert-laravel#13]
Hi,

I've installed this components using composer on Laravel 5 but I can't get it to work.
All I get for every request is "No API key provided." even though I've set them in config/cloudconvert.php.

I've tried re-installing multiple times but always end up with the same results.

Any ideas?

**Comment by robbiepaul** [comment]
Strange, I haven't come across anyone with this issue before. Have you tried manually setting the key as a temporary solution?

``` php
CloudConvert::setApiKey('api_key_goes_here');
```

Just put that before you start the conversion process, let me know if it works.

**Comment by pierrepavlov** [comment]
Yeah, I ended up setting it manually for now and that worked. No idea why I can't use the configuration file though.

**Comment by robbiepaul** [comment]
I just tested this on a fresh installation of Laravel 5.1, it's working exactly as expected. Providing the API key in `config/cloudconvert.php` works.

My advice would be to double check the documentation
