### ISSUE TITLE
laravel 5.1.20 (LTS) composer won't install

### ISSUE THREAD

**Issue by Sheby** [robbiepaul/cloudconvert-laravel#14]
"Your requirements could not be resolved to an installable set of packages."

I see this has been  a poblem before, can you update the code please?

**Comment by robbiepaul** [comment]
The issue before was resolved.

I just installed the package successfully on a blank Laravel 5.1.20 project.

Check you have `"robbiep/cloudconvert-laravel": "2.*"` or maybe one of your other packages are conflicting somehow?

**Comment by Sheby** [comment]
A plugin for Socialite is requiring a different version of guzzlehttp/guzzle, removed it and then this plugin installs, but i need both of them, is there any way to resolve this?

And thanks alot for a promt reply

Update: socialatie plugin uses guzzle 6 and yours 5, any way to  resolve this?
Update2: required older version of conflicted plugin, works fine now, thanks for help!

**Comment by robbiepaul** [comment]
Glad you got to the bottom of it. No problem!

**Comment by edbentinck** [comment]
I just ran into the same issue. Any chance of updating the package for guzzle 6? I tried but it's a bit beyond me :disappointed:

**Comment by robbiepaul** [comment]
@edbentinck I've updated the `composer.json` to accept both Guzzle ~5.0 and ~6.0.

I haven't tested it yet though as I haven't used a package that depends on Guzzle 6.0.

Can you `composer [update/require] robbiep/cloudconvert-laravel` and let me know if it fixes your problem?

**Comment by edbentinck** [comment]
Thanks for your swift response, @robbiepaul. Unfortunately Guzzle 6 has many breaking changes from Guzzle 5, [as mentioned here](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md), so your package errors out in a few places.

I was able to fix some of the errors manually, but some others I wasn't. I'll try again and let you know how I get on. As far as I can tell it should only be the HttpClientAdapter that causes problems.

**Comment by robbiepaul** [comment]
Wow you're right, many breaking changes! Out of curiosity which package that you're using requires Guzzle 6?

I'll rewrite `HttpClientAdapter` just as soon as I get time or feel free to submit a pull request

**Comment by edbentinck** [comment]
I had Guzzle 6 installed for [this package](https://github.com/maknz/slack). It seems that they actually support various versions of Guzzle, which I hadn't realised before. I've just downgraded my version of Guzzle to be able to use your package which now works (it's great, by the way!). Hopefully it won't have caused any side effects. 

If I get the time I will continue to try and refactor your package to support Guzzle 6. I got past a few errors, but got stuck on a `400 Bad Request` error that someone else has [already mentioned in the issues here](https://github.com/robbiepaul/cloudconvert-laravel/issues/9). I'm short for time so for now I'll stick with a working version :)

**Comment by robbiepaul** [comment]
I'm glad you got it working. I'm going to write an adapter for Guzzle 6 anyway, as I'm sure people will be moving across soon

**Comment by robbiepaul** [comment]
I've written another implementation of `HttpClientInterface` for Guzzle 6 and added some version checking in the `HttpClient`.

It's working perfectly for both Guzzle 5 and Guzzle 6.

**Comment by edbentinck** [comment]
Awesome! Thanks @robbiepaul
