### ISSUE TITLE
Issues with density (Laravel 4.2)

### ISSUE THREAD

**Issue by janmikusch** [robbiepaul/cloudconvert-laravel#15]
Hey, i have some issues when I'm converting my files. The Image-Files are resizing correctly, but the density won't change to 72.

Here is my code.
`CloudConvert::file('upload/'.$filename)->withOptions([
                    'resize' => $newWidth.'x'.$newHeight,
                    'density' => '72'
                ])->to('files/img/'.$fn.'.jpg');`

I'm using Laravel 4.2

**Comment by robbiepaul** [comment]
Have you tried the same with but with the API Console? Just to make sure it's not an API issue.

https://cloudconvert.com/apiconsole

(take note of the converteroptions)

**Comment by janmikusch** [comment]
I did it with the API Console. Same result.
`$api->convert([
    "input" => "upload",
    "inputformat" => "jpg",
    "outputformat" => "jpg",
    "converteroptions" => [
        "resize" => "720x480",
        "density" => "72",
    ],
    "file" => fopen('input.jpg', 'r'),
])
->wait()
->download();`

The density won't change.

**Comment by josiasmontag** [comment]
Hi, it seems to be an API issue and it is not related to the Laravel wrapper. Could you please quickly send your input.jpg to support@cloudconvert.com for further testing. Thanks.

**Comment by robbiepaul** [comment]
Many thanks @josiasmontag
