### ISSUE TITLE
How to retrieve callback parameters 

### ISSUE THREAD

**Issue by bachras** [robbiepaul/cloudconvert-laravel#23]
I am using callback function and I want to notify the user when conversion is finished. How to retrieve the process id which is finished with callback? Will multiple conversions will work at the same time?
Thank you in advance.

**Comment by robbiepaul** [comment]
You can get the `id` like this

``` php
$cloudConvert = CloudConvert::useProcess($_REQUEST['url']);
$id = $cloudConvert->getProcess()->id;
```

Yes it should work with multiple conversions at the same time

**Comment by bachras** [comment]
Now I get this error: 
`Fatal error: Cannot access private property RobbieP\CloudConvertLaravel\Process::$id`

Do you have any ideas?

**Comment by robbiepaul** [comment]
Yea, just `composer update robbiep/cloudconvert-laravel` should work now

**Comment by bachras** [comment]
It is working now. Thanks for fixing it.
