### ISSUE TITLE
Getting the video thumbnail

### ISSUE THREAD

**Issue by chrisbell08** [robbiepaul/cloudconvert-laravel#25]
Hey,

Thanks for putting this repo together, saved me a ton of time getting the integration with cloud convert working.

Is it possible to also push the video thumbnail up to s3 with a converted video?

I'm converting an mp4 to webm and have seen in the cloud convert docs you can get the thumbnail, I assume using the withOptions method but not sure how I would then push it up to s3 with the video.

Cheers

**Comment by robbiepaul** [comment]
You're right you would use `withOptions` but to be honest I'm not 100% sure what the format of the values are, my guess would be:

``` php
CloudConvert::file('/a/local/path/video.mp4')
             ->withOptions([
                     'thumbnail_count' => '1',
                     'thumbnail_size' => '640x480',
                     'thumbnail_format' => 'png'
             ])
             ->to(CloudConvert::S3('converted.webm'));
```

If that doesn't work my advice would be to fire off an email to support@cloudconvert.com. They're extremely helpful.

Let me know how you get on.

**Comment by chrisbell08** [comment]
That worked perfect. It creates a new folder on s3 and adds in the video with a thumbnail. Thanks!
