### ISSUE TITLE
accessing the process id

### ISSUE THREAD

**Issue by chrisbell08** [robbiepaul/cloudconvert-laravel#26]
Hey,

I need to access the process ID when I make a request so I can save it to a DB and do some stuff with it when the callback comes back from cloud convert. The only way I can do this is by changing the $process property on the cloud convert class to public then doing this:

```
    $cloudconvert =  CloudConvert::file($url)->withOptions([
            'thumbnail_count' => '1',
            'thumbnail_size' => '203x113',
            'thumbnail_format' => 'png'
        ])->callback(env('SITE_URL') . '/events/videoConverted')->convert('webm');

        $processId = $cloudconvert->process->id;
```

The only issue with this is that i've had to override something in your core library which isn't ideal as I would then have to prevent it from updating.

Is there currently a better way to access the ID? If not would it be possible to add this in?

**Comment by robbiepaul** [comment]
This should work:

``` php
$processId = $cloudconvert->getProcess()->id;
```

**Comment by chrisbell08** [comment]
Works a treat thanks!

**Comment by robbiepaul** [comment]
Glad to help!
