### ISSUE TITLE
How to enable CacheControl while uploading to Amazon S3

### ISSUE THREAD

**Issue by AmirAmin** [robbiepaul/cloudconvert-laravel#33]
Hello,

I have two questions:

1) How can i enable CacheControl while uploading to Amazon S3? as it saves a lot of money on the long run.

2) Does CloudConvert have watermark feature ? for example if i want to add a watermark or website name on the converted images.

Best Regards,
Amir Amin

**Comment by josiasmontag** [comment]
1) It is supported by CloudConvert itself, but I am not sure if the laravel wrapper has this functionality yet. See https://cloudconvert.com/api/s3 (output.s3.cachecontrol)
2) Watermarking is currently not supported by CloudConvert.

**Comment by robbiepaul** [comment]
Yeah you can just add it to the list of output arguments, if we use the same example from yesterday it would be:

``` php
CloudConvert::file('http://www.gnfiliaton.gr/sites/default/files/20131231103232738561744.pdf')
            ->withOptions([
                'quality' => 80,
                'resize' => '500x400',
                'resizemode' => 'crop' // (optional) or 'scale' 
            ])
            ->callback('http://url.com/callback')
            ->convert( CloudConvert::S3('jpg', [
                'path' => 'uploads/catalogue/issue/',
                'cachecontrol' => 'max-age=172800'
            ]));
```

For watermarking perhaps use the [Intervention Image](http://image.intervention.io/) package in conjunction with Laravel's cloud storage file system (see the [docs](https://laravel.com/docs/master/filesystem))

**Comment by AmirAmin** [comment]
Thanks Brothers,

@robbiepaul It worked perfect, But it has to be 'CacheControl' not 'cachecontrol' as the lowercase will return the following error message:
`"Saving to S3 failed: Unexpected key 'cachecontrol' found in params (Code: UnexpectedParameter)"`

I will check Intervention Image package for the watermark.

Thanks again

**Comment by robbiepaul** [comment]
Glad it worked!
