### ISSUE TITLE
encoding 

### ISSUE THREAD

**Issue by digxtal16** [robbiepaul/cloudconvert-laravel#34]
Hello!
How to set the encoding?
I use:
$variables = ['template' => 'шаблон_1 kjf'];
CloudConvert::file(public_path().'/files/otch.docx')->templating($variables)->to('pdf');
and get http://clip2net.com/s/3AhDTAc
I tried "mb_convert_encoding", "iconv" but this not helped me.

**Comment by robbiepaul** [comment]
Hmm not sure. I'm not at my computer today so I can't check. Have you tried the same thing using the [CloudConvert API Console](https://cloudconvert.com/api/console)? Does it work there?

**Comment by digxtal16** [comment]
Did not work out

**Comment by robbiepaul** [comment]
I suggest emailing support@cloudconvert.com

They're always helpful with API issues.
