### ISSUE TITLE
Call to a member function getFormat() on null, after a commit from 20. June 2016

### ISSUE THREAD

**Issue by rgozdzialski** [robbiepaul/cloudconvert-laravel#36]
Hi,

We've been having problems with `conversionTypes()` method. We used it like this:

`$types = CloudConvert::input('jpg')->conversionTypes();`

and it worked fine. After `composer update` we get a **[fatal error](http://i.imgur.com/clSbBgY.jpg)**. Basically, `CloudConvert->getOutputFormat()` suddenly fails.

Took us a while to understand what is going on, because for some of the team members the code worked, for others - not. Turned out that some of us had newer version of your package and for those the fatal error occurred. 

Anyway, seems like it all comes down to **[the change](https://github.com/robbiepaul/cloudconvert-laravel/commit/d871d75e4358f06cb9e2a9034efe797b3b7f429c#diff-63e23132b7eed0d038b3007d043b1738L768)**, where this line

`return isset($this->output) ? $this->getOutput()->getFormat() : $this->output_format;`

changed to this one:

`return !isset($this->output_format) ? $this->getOutput()->getFormat() : $this->output_format;`

It's hard at this point to be more specific, but hopefully it's enough for you to take a look at possible problems.

**Comment by robbiepaul** [comment]
Thanks for reporting this, I'll have a look in to it

**Comment by robbiepaul** [comment]
I've reverted this back to it's original function in `v2.3`
