### ISSUE TITLE
Multiple File Download to specific folder

### ISSUE THREAD

**Issue by jAddict7** [robbiepaul/cloudconvert-laravel#37]
Hi Team,
Thanks for the excellent plugin. Am trying to convert PDF to JPG where multiple images are converted and received. I just need to know how to save all the files to a specific folder, My code
`CloudConvert::file('http://test.com/Test.pdf')->to('jpg');`

Also I tried,
`CloudConvert::file('http://test.com/Test.pdf')->to('jpg', ['path' => $filePath]);`

Everything saves in public folder and unable to route to a specific folder inside my web application. Is it possible to save all files inside specific folder?

**Comment by robbiepaul** [comment]
I would suggest:

``` php
CloudConvert::make('http://test.com/Test.pdf', 'pdf', 'jpg')->save('/path/to/folder');
```

Or this should save it in a folder called `test.jpg`

``` php
CloudConvert::file('http://test.com/Test.pdf')->to('/path/to/folder/test.jpg');
```

**Comment by jAddict7** [comment]
Thanks for your reply Paul, I have tried this code
`CloudConvert::make('http://example.com/test.pdf', 'pdf', 'jpg')->save('/icons/');`
and got the following error,
`Output format provided does not match the format converted`

And also Input may be anything like Doc, Excel, PDF, so specifying as parameter is not option for me I think so brother. PDF with 144 pages or Excel with 100 pages may be given and need to route to specific folder in public_path. Is there possibility to use **downloadAll** option of the CloudConvert PHP API??

**Comment by robbiepaul** [comment]
Yea, my plan is to rewrite this wrapper for `v3.0` and use the excellent official CloudConvert PHP package as the core, however it's probably a few months away yet as I have a lot of stuff going on at the moment.

Did you try:

``` php
CloudConvert::file('http://test.com/Test.pdf')->to('/path/to/folder/test.jpg');
```

?

**Comment by jAddict7** [comment]
Yeah thats great to hear. Yes, tried that but got
`File not writable or no data available: /icons/test.jpg`
And hope that will provide single.

**Comment by robbiepaul** [comment]
Does the '/icons/' folder exist?

**Comment by robbiepaul** [comment]
I only ask because I've used this code on a previous project when converting multiple page PowerPoints to image files:

``` php
CloudConvert::file($uploadedFile)->dpi(300)->quality(80)->withOptions(['resize' => '1024x768'])->to($slideshowPath.'/image.jpg');
```

I remember I had to explicitly make sure `$slideshowPath` existed first. eg:

``` php
\File::exists($slideshowPath) or \File::makeDirectory($slideshowPath);
```

**Comment by jAddict7** [comment]
Yes the folder is present

**Comment by robbiepaul** [comment]
Strange, I just checked the project I mentioned in the example above and it's still creating all the images correctly in a sub-directory. Are you sure you have write access on the folder?
