### ISSUE TITLE
Class 'App\Http\Controllers\CloudConvert' not found

### ISSUE THREAD

**Issue by JonoHall** [robbiepaul/cloudconvert-laravel#41]
I found your instructions great, got it installed, but came up with this error.

It took me a day or so trying to figure it out before consulting the gurus on IRC. I'm quite new to Laravel, so it didn't occur to me that you need to add the class to your controller before you can use it (now it seems obvious).

For anyone else trying to solve this, you need to add the following to the top of your page:
`use RobbieP\CloudConvertLaravel\Facades\CloudConvert;`

I'd recommend adding this into your readme just above the part you mention "Now you can use CloudConvert in your application!".

Thanks for your app!

**Comment by reinierkors** [comment]
Or you can add it to your **app.php aliases**:
`'CloudConvert' => RobbieP\CloudConvertLaravel\Facades\CloudConvert::class,`

and then just do:
`use CloudConvert;`

**Comment by robbiepaul** [comment]
Thanks @reinierkors 

The ServiceProvider should also automatically register the facade
