### ISSUE TITLE
Creating Pictures Thumbnails

### ISSUE THREAD

**Issue by AmirAmin** [robbiepaul/cloudconvert-laravel#43]
Hello,

Right now, I am using this package to convert PDF to JPGs, and it is doing a wonderful job.

My Question is: Is there a option to create Tumbs/Thumbnails from the pictures as well?, so the callback for ex. would return the normal image, and its thumbnail.

Note: I need this function as i am creating flipping book from the returned images, and i want the thumbnails for the TOC.

Regards,
Amir Amin

**Comment by robbiepaul** [comment]
As far as I'm aware the thumbnail option is only available when converting videos.

You could create a separate process to create a thumbnail from the first page of the PDF?

**Comment by AmirAmin** [comment]
Yes, I know that the thumbnails can be created when converting videos, but i though there may be for pdf as well.

I also thought about creating another process to create thumbnails, but it is a matter of cost and time to complete both processes specially while converting large files.

Thanks a lot bro.

**Comment by AmirAmin** [comment]
Hello Again,

After more than a year, Is there a solution for this now?
