### ISSUE TITLE
File does not get converted (?)

### ISSUE THREAD

**Issue by reinierkors** [robbiepaul/cloudconvert-laravel#44]
I'm trying to convert .flv to .mp4.

When uploading:
`CloudConvert::file($file)->to(CloudConvert::S3($id.'.mp4'));`

Everything seems to work fine, but when I download and open the generated file it seems to be in flv format still 😕.

When manually converting it on the site itself, I get the correct video in flv format.

Any guidance would be appreciated.

**Comment by robbiepaul** [comment]
This is strange, I was testing Amazon S3 video conversion only a few months ago.

I'll have a look in to it.

**Comment by reinierkors** [comment]
Alright,

After some testing I found the issue on my side. Also, maybe change the config file to 'key' and 'secret' for Amazon S3 like filesystems does.

Cheers.
