### ISSUE TITLE
Error when converting docx to pdf

### ISSUE THREAD

**Issue by dandyfirmansyah18** [robbiepaul/cloudconvert-laravel#45]
When i converting my document from docx to pdf. i have this error  'cURL error 7: Failed to connect to api.cloudconvert.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

What should I do ?
Sorry i am bad in English

Thanks 
Dandy F

**Comment by josiasmontag** [comment]
Seems to be a network issue. Firewall? This issue is not related to the Laravel wrapper. For further investigation please contact us directly via support@cloudconvert.com.

**Comment by dandyfirmansyah18** [comment]
oke oke thanks
