### ISSUE TITLE
How i will set video resolution of new video output file

### ISSUE THREAD

**Issue by rizwanmcs** [robbiepaul/cloudconvert-laravel#46]
Hi guys,
i want to convert video file .mov to mp4 but i don't know how i will set the resolution and buffer size for output file.
Thanks
`CloudConvert::file('/public/uploads/gdtbgds125846.mov')->to('/public/convert/gdtbgds125846.mp4');`

**Comment by robbiepaul** [comment]
You need to use `withOptions` there's documentation in the readme. Also check the official API docs for all the available converter options: https://cloudconvert.com/api/console
