### ISSUE TITLE
Get file information

### ISSUE THREAD

**Issue by AmirAmin** [robbiepaul/cloudconvert-laravel#47]
Hello,

There is a method to extract file metadata from PDF, image, video and audio files, is it included in this package? and how to use it.

For more details about it, kindly check the following link:
https://cloudconvert.com/api/info

Regards,

**Comment by robbiepaul** [comment]
Hi Amir,

This functionality exists in the Laravel wrapper. I haven't had a chance to update the README file yet (feel free to make a PR)

This example code should work though:

```php
$response = CloudConvert::file('https://server.com/path/to/video.mp4')
                        ->info()
                        ->response();
```

**Comment by AmirAmin** [comment]
Dear Robb,

Thanks for your wonderful efforts.
Can you please double check it ? as i have tried it with different links, servers, and it keep giving timeout.

Regards,,

**Comment by robbiepaul** [comment]
I've issued a hotfix, please do a `composer update`

**Comment by AmirAmin** [comment]
Wonderful, it works like a charm.

Tnx Bro.
