### ISSUE TITLE
Symfony UploadedFile

### ISSUE THREAD

**Issue by nomadme** [robbiepaul/cloudconvert-laravel#48]
Thank you for the package. 

How can I convert file using Symfony Uploaded file as an input and saving it somewhere else?

`app('cloudconvert')->file($uploadedFile)->to('pdf', true)->save(storage_path())`

> Client error: `GET https://host123d1qp.cloudconvert.com/download/~qPUuwEqiICsPI4AKiI1B-iUBtXY` resulted in a `400 Bad Request` response:
> {"error":"This process does not have any output files.","code":400}

**Comment by robbiepaul** [comment]
Please see the example in the README for using uploaded file

```php
if (Input::hasFile('photo'))
{
    CloudConvert::file( Input::file('photo') )->to('/a/local/path/profile_image.jpg');
}
```
