### ISSUE TITLE
Laravel 5.4 Compatibility

### ISSUE THREAD

**Issue by ajarti** [robbiepaul/cloudconvert-laravel#49]
HI there,

Looks like you might need to update all the old Share references to Singleton for compatability.

As per: https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736

No time to pull req at the mo :(

**Comment by robbiepaul** [comment]
Thanks for letting me know.

I've pushed up a patch that should fix this: 5671a435ecda5797ac108d7c97a6ebc3985729e7

Please run `composer update robbiep/cloudconvert-laravel`

**Comment by ajarti** [comment]
@robbiepaul that is excellent and super fast fix!! .. 

Thanks.
