### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by natsu90** [robbiepaul/cloudconvert-laravel#5]
I have a freshly installed Laravel 5. Installing "robbiep/cloudconvert-laravel": "~2.0" give me the following error, `Your requirements could not be resolved to an installable set of packages.`

**Comment by spdaly** [comment]
Same here... Any update on the problem?

**Comment by robbiepaul** [comment]
I'll have a look at it asap. 
Laravel 5 was still in beta when I released this package, my guess is it's something straight forward

**Comment by spdaly** [comment]
I hope so... I'm trying to get it to work in an L5 app and I'm having issues trying to convert an uploaded file.  It looks like the input file gets lost as it goes through the process steps.  The CC dashboard says that there is an error uploading the file.  Debugging shows that the $file is null/empty when the upload is attempted.

**Comment by robbiepaul** [comment]
Hi. I've updated the package to be compatible with Laravel 5. See 5b9489359745a2c9f0b205937cf21cf0d7aa9913

Update your composer.json to version 2.1
