### ISSUE TITLE
"Could not be converted"

### ISSUE THREAD

**Issue by fusigabs** [robbiepaul/cloudconvert-laravel#50]
Hi, thanks for this repo...really helpful. I implemented it and it works great for images, and pushes them to s3 just fine. But when I try any vide, I get "Could not be converted". Anyone had this issue before and any ideas what caused it?
```php
/** store function in the controller **/
public function store()
{
    if (Input::hasFile('photo')){
        CloudConvert::file(Input::file('photo'))->convert(CloudConvert::S3('TestVideo.webm'));
        return redirect('/upload');
    }
}

/** upload form in view **/
{!! Form::open(['action' => 'UploadController@store', 'method'=>'POST', 'files' => true]) !!}
    <div class="form-group">
          {!! Form::label("photo", "Upload Image:") !!}
          {!! Form::file("photo", null, ['class'=>'form-control']) !!}
     </div>
     <div class="form-group">
            {!! Form::submit("Create", ['class'=>'btn btn-success pull-right']) !!}
     </div>
{!! Form::close() !!}
```

This works well for images, both saving to a local folder and to s3, but I get this "Count not be converted" message for videos. My test video is 1minute in length.

Thanks in advance for any help.

**Comment by josiasmontag** [comment]
This issue seems to be related to the input file / CloudConvert directly and not the Laravel wrapper. Can you convert the same file on the CloudConvert website directly? If not, please contact us at support@cloudconvert.com and provide the example file.

**Comment by fusigabs** [comment]
The issue was really with my server. I checked my Apache logs and realized the `max_post_size` needed to be increased in php.ini. Same file works on cloudconvert website, so will look at what more I need to get my server accepting these large post requests. Thanks @josiasmontag
