### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by brickgale** [robbiepaul/cloudconvert-laravel#53]
I'm using Laravel5.2, there is already guzzlehttp on vendor folder. I'm not sure why is it giving me SSL certificate problem when I'm still doing it on local. Do we need SSL for calling the api of Cloud Convert?

**Comment by robbiepaul** [comment]
Sounds like an issue with your local environment. You shouldn't need to touch self signed certificates.

**Comment by brickgale** [comment]
So basically CloudConvert needs SSL? Thanks. I tried on staging server with SSL, it works fine. I usually just do 'php artisan serve' on local that's why.

**Comment by brickgale** [comment]
@robbiepaul you were right, its just a local problem, not CloudConvert. Found my solution in SO. https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

Windows 10
XAMPP
Laravel 5.2 (php artisan serve)

**Comment by ImmanuelJL** [comment]
@brickgale hi i face the same problem and it solved also on local with your link to stackoverflow. My question is, is it a must to have SSL on my live server??? or i can convert it without ssl???

**Comment by brickgale** [comment]
@ImmanuelJL i think it won't mind if you have SSL on live if it's running on a linux server usually. This is just basically because of my local dev environment running on xampp.

**Comment by ImmanuelJL** [comment]
@brickgale oh i see, thanks brooo
