### ISSUE TITLE
if using Laravel 

### ISSUE THREAD

**Issue by chantrea** [robbiepaul/cloudconvert-laravel#56]
I tried to convert any videos from users upload to mp4. 
1.) Is that mp4 always take care the best conversion bit rate and small size and will that video support all browsers like safari, IE, Chrome, Firefox, Opera, etc... 

in my code
CloudConvert::file($uploadedFile->getRealPath())->quality(70)->to(CloudConvert::S3('users/videos/'.$timestamp.".mp4"));

Error I got 
Non-static method RobbieP\CloudConvertLaravel\CloudConvert::file() should not be called statically

**Comment by robbiepaul** [comment]
do you have `use RobbieP\CloudConvertLaravel\CloudConvert` that the top of your class?

You should be using the facade instead

**Comment by christianahvilla** [comment]
Hi, I have the same problem. Did you resolve the issue already?

**Comment by MuhammedTNCR** [comment]
Hi @robbiepaul i did what you said with use statement but i am still getting the same error. Any help?
