### ISSUE TITLE
convert PDF and store it on database

### ISSUE THREAD

**Issue by johnef** [robbiepaul/cloudconvert-laravel#57]
Hi I came here across a long search after my requests.
I am using Laravel 5.2

What I am looking for is.
I have one PDF file witch is 50 page.
I need to convert all to two types of images
type one
skip the first image, and start from the second
and combined it with the third, and so on combing 4-5 and 6-7, 8-9 .... 
then store them into my database.

type two just convert the PDF to images and store it in my database.

Can this package help me doing so??

Regards

**Comment by robbiepaul** [comment]
Yes it can help
