### ISSUE TITLE
Cannot convert file upload...

### ISSUE THREAD

**Issue by spdaly** [robbiepaul/cloudconvert-laravel#6]
I'm not having any luck converting an uploaded Powerpoint file to PDF.  I'm using L5.  The uploaded file doesn't have an extension so CC returns a cannot convert this format error message.  I have made several changes to the library code with no luck.  Now I'm running in circles...

Any help???

**Comment by robbiepaul** [comment]
Hi. I've updated the package to be compatible with Laravel 5. See 5b9489359745a2c9f0b205937cf21cf0d7aa9913

Update your composer.json to version 2.1

**Comment by spdaly** [comment]
Composer cannot find the 2.1 tag.

**Comment by robbiepaul** [comment]
Apologies, I forgot to push up the tags. Should work now

**Comment by robbiepaul** [comment]
Also use "2.*" instead of "2.1"
