### ISSUE TITLE
Not working for Laravel 6.x

### ISSUE THREAD

**Issue by anilkumar219** [robbiepaul/cloudconvert-laravel#66]
This package isn't working for Laravel 6.x

**Comment by piep14** [comment]
@robbiepaul  Can you support Laravel 6 ? Thank you.

**Comment by darcyrailip** [comment]
@robbiepaul Following up on this. Thanks.

**Comment by robbiepaul** [comment]
Apologies for the slow response on this, I don't use PHP any more and don't have much time to support this package. 

I have released `v3.0` that should support Laravel 6.x however I suggest using the [official CloudConvert Laravel package](https://github.com/cloudconvert/cloudconvert-laravel)
