### ISSUE TITLE
Installing the package in Laravel 5.1.6 not possible

### ISSUE THREAD

**Issue by rgozdzialski** [robbiepaul/cloudconvert-laravel#8]
**CASE 1**

I'm running Laravel 5.1.6. I follow the install instructions for Laravel 5+ from the GitHub project. After the **"robbiep/cloudconvert-laravel": "2.*"** dependency is added to **composer.json**, I run `composer update` and I get the following error: http://i.imgur.com/zhU3WXU.jpg.

Basically, it claims that the **BroadcastServiceProvider** is missing, which is actually correct. The provider files are gone after your package is required and tried to be installed.

The BroadcastServiceProvider is a part of upgrate to Laravel 5.1: http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0.

**CASE 2**

When I try `composer install` instead, the process is successful, but the **CloudConvertLaravelServiceProvider** is not created, file of this name does not exist in the project. Then, running `php artisan vendor:publish` throws this: **Class ''RobbieP\CloudConvertLaravel\CloudConvertLaravelServiceProvider'' not found**.

Not really sure what is going on. Maybe the documentation on GitHub is not up to date. Maybe I'm doing something incorrectly. In any case, would be nice to get an answer or suggestions. Thanks!

**Comment by robbiepaul** [comment]
I haven't had a chance yet but I'll work on 5.1 support this weekend

**Comment by rgozdzialski** [comment]
Thanks for quick reply and good luck.

**Comment by vinicius73** [comment]
any news?
